/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package common;

import application.product.Product;
import application.storage.ProductGroup;
import java.util.ArrayList;
import java.util.List;

/**
 * A notice generated by the notice report director
 *	holds a product group and a product that don't share the same type of unit 
 *	in the three month supply
 * @author Stephen Kitto
 */
public class Notice {
	
	private ProductGroup productGroup;
	private List<Product> product;
	
	public Notice(ProductGroup pg, Product p){
		productGroup = pg;
		product = new ArrayList<Product>();
		product.add(p);
	}

	public void addProduct(Product p) {
		product.add(p);
	}

	public ProductGroup getProductGroup() {
		return productGroup;
	}

	public List<Product> getProducts() {
		return product;
	}
	
}
